### ISSUE TITLE
click-through option

### ISSUE THREAD

**Issue by eMKey1988** [UberSwe/Tarkov-Map-Overlay#13]
- try to add an click-through option to the menu or an hotkey that handles that

**Comment by eMKey1988** [comment]
is F3 okay as the hotkey? or should that be also changeable by the user?

**Comment by uberswe** [comment]
> is F3 okay as the hotkey? or should that be also changeable by the user?

you can define a default key but it would be nice if it could be changed.

**Comment by uberswe** [comment]
fixed in #17
