### ISSUE TITLE
Use Properties.Settings for the application state

### ISSUE THREAD

**Issue by uberswe** [UberSwe/Tarkov-Map-Overlay#16]
Currently a folder with a save file is made to save the application state. It would be better and more user friendly id we use Properties.Settings for this. There may be alternatives to Properties.Settings which I have not considered which would also be good choices.

See the following links for more info

https://docs.microsoft.com/en-us/archive/blogs/patrickdanino/user-settings-in-wpf
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-write-user-settings-at-run-time-with-csharp?view=netframeworkdesktop-4.8

**Comment by eMKey1988** [comment]
this is a little new to me, because i never used this technique before. but i think i'm fine with that.
( using the Binaryformatter was best for me in Unity3D )^^

**Comment by uberswe** [comment]
fixed in #17
