### ISSUE TITLE
A way to add map files and save 

### ISSUE THREAD

**Issue by ghstdan** [UberSwe/Tarkov-Map-Overlay#6]
looking into creating a way to edit the resource folder to add my own image files and save this. Either through a separate folder or the browse function and save all maps for next launch. Great piece of software by the way

**Comment by uberswe** [comment]
Thank you and I appreciate that you took the time to open an issue. Really great feedback. I think this is related to #4 and could be done at the same time. It is something I want to implement and I might have some time to look at it over the weekend.

**Comment by eMKey1988** [comment]
Maybe i can look into that to help you out with that one, if you are okay with that.

**Comment by uberswe** [comment]
> Maybe i can look into that to help you out with that one, if you are okay with that.

Sure, that would be great @eMKey1988 just open a pull request and I will review and merge it and make a new build.

**Comment by eMKey1988** [comment]
the thing is...i am almost done, but i don't know how this works with git...can you help me with that?

**Comment by uberswe** [comment]
Sure, the recommended way is to fork this repository. Then clone the repository locally which is possible with the [Github Desktop](https://desktop.github.com/) app but you can also just use the cli command. Commit your changes and push them to your fork. Then open a pull request from your fork to this repository.

Feel free to message me on discord for more help: uberswe#9999
