### ISSUE TITLE
Ability to zoom loaded images

### ISSUE THREAD

**Issue by uberswe** [UberSwe/Tarkov-Map-Overlay#7]
Requested from this tweet :D https://twitter.com/Humbi_Bambi/status/1244934612536745984

I imagine this working by simply using the scroll wheel on top of the image and it zooms inside the square container of the application.

**Comment by eMKey1988** [comment]
got it working right now, but there is a conflict with panning the zoomed image and your pice of code that makes the whole window draggable. i had to change it so you can only drag the window by click and hold the mouse on the menu button ( dragging with the background will also work if it's not 100% transparent ).
Another problem i have in mind is that ingame the cursor is locked to the crosshair most of the time, so you can't perform panning or zooming if you aren't able to have the cursor hovering over the actual image.
.

**Comment by uberswe** [comment]
> got it working right now, but there is a conflict with panning the zoomed image and your pice of code that makes the whole window draggable. i had to change it so you can only drag the window by click and hold the mouse on the menu button ( dragging with the background will also work if it's not 100% transparent ).
> Another problem i have in mind is that ingame the cursor is locked to the crosshair most of the time, so you can't perform panning or zooming if you aren't able to have the cursor hovering over the actual image.
> .

Yes, I think the first issue is ok, we can live with that. Regarding the second issue I also would like to disable the application from being interactive while playing. Currently it's not possible to cover the middle of the screen for example since the cursor sits there and will interact with the application. It's also annoying if you accidentally click the window when you open your inventory as that will give you a free moving cursor that allows you to interact with the window.
